apiVersion: apps/v1
kind: Deployment
metadata:
  name: front_
  labels:
    app: front_
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front_
  template:
    metadata:
      labels:
        app: front_
    spec:
      containers:
        - name: front_
          image: username/front_:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
